export const ALLCONTINENTS_PENDING = 'ALLCONTINENTS_PENDING';
export const ALLCONTINENTS_SUCESS = 'ALLCONTINENTS_SUCESS';
export const ALLCONTINENTS_FAILED = 'ALLCONTINENTS_FAILED';
export const COUNTRIES_LIST_PENDIG = 'COUNTRIES_LIST_PENDIG';
export const COUNTRIES_LIST_SUCCESS = 'COUNTRIES_LIST_SUCCESS';
export const COUNTRIES_LIST_FAIL = 'COUNTRIES_LIST_FAIL';
