export const TOGGLE_SIGNIN = 'TOGGLE_SIGNIN';
export const TOGGLE_REGISTER = 'TOGGLE_REGISTER';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const GET_USERS_PENDING = 'GET_USERS_PENDING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const CREATE_POST_PENDING = 'CREATE_POST_PENDING';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED';

export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';

export const FETCH_ONE_POST_PENDING = 'FETCH_ONE_POST_PENDING';
export const FETCH_ONE_POST_SUCCESS = 'FETCH_ONE_POST_SUCCESS';
export const FETCH_ONE_POST_FAILED = 'FETCH_ONE_POST_FAILED';

export const DELETE_POST_PENDING = 'DELETE_POST_PENDING';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';

export const UPDATE_POST_PENDING = 'UPDATE_POST_PENDING';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILED = 'UPDATE_POST_FAILED';

export const SUBSCRIBE_PENDING = 'SUBSCRIBE_PENDING';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
export const SUBSCRIBE_FAILED = 'SUBSCRIBE_FAILED';

export const FETCH_SUBS_PENDING = 'FETCH_SUBS_PENDING';
export const FETCH_SUBS_SUCCESS = 'FETCH_SUBS_SUCCESS';
export const FETCH_SUBS_FAILED = 'FETCH_SUBS_FAILED';

export const FETCH_COMMENTS_PENDING = 'FETCH_COMMENTS_PENDING';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILED = 'FETCH_COMMENTS_FAILED';

export const COMMENTING_PENDING = 'COMMENTING_PENDING';
export const COMMENTING_SUCCESS = 'COMMENTING_SUCCESS';
export const COMMENTING_FAILED = 'COMMENTING_FAILED';

export const UNSUBSCRIBE_PENDING = 'UNSUBSCRIBE_PENDING';
export const UNSUBSCRIBE_SUCCESS = 'UNSUBSCRIBE_SUCCESS';
export const UNSUBSCRIBE_FAILED = 'UNSUBSCRIBE_FAILED';

export const CREATE_QUERY_PENDING = 'CREATE_QUERY_PENDING';
export const CREATE_QUERY_SUCCESS = 'CREATE_QUERY_SUCCESS';
export const CREATE_QUERY_FAILED = 'CREATE_QUERY_FAILED';

export const FETCH_QUERIES_PENDING = 'FETCH_QUERIES_PENDING';
export const FETCH_QUERIES_SUCCESS = 'FETCH_QUERIES_SUCCESS';
export const FETCH_QUERIES_FAILED = 'FETCH_QUERIES_FAILED';

export const DELETE_QUERY_PENDING = 'DELETE_QUERY_PENDING';
export const DELETE_QUERY_SUCCESS = 'DELETE_QUERY_SUCCESS';
export const DELETE_QUERY_FAILED = 'DELETE_QUERY_FAILED';

export const LIKE_PENDING = 'LIKE_PENDING';
export const LIKE_SUCCESS = 'LIKE_SUCCESS';
export const LIKE_FAILED = 'LIKE_FAILED';

export const UNLIKE_PENDING = 'UNLIKE_PENDING';
export const UNLIKE_SUCCESS = 'UNLIKE_SUCCESS';
export const UNLIKE_FAILED = 'UNLIKE_FAILED';
